FROM python:3.10
ENV PYTHONUNBUFFERED 1

RUN curl -sSL https://install.python-poetry.org | python3 -
RUN ln -s $HOME/.local/bin/poetry /usr/local/bin/poetry

# Allows docker to cache installed dependencies between builds
COPY pyproject.toml poetry.lock ./
RUN poetry config installer.max-workers 4
RUN poetry config virtualenvs.create false && poetry install --without dev

# Adds our application code to the image
COPY . /app
WORKDIR app

EXPOSE 8000
