version: "3.8"

services:
  server:
    build:
      context: ./app
      dockerfile: ../docker/dockerfile.server
    volumes:
      - ../app:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --reload
    env_file:
      - .env